In [26]:
import numpy as np
import h5py


In [27]:
base = "/cosmos_storage/simulations/MTNG"

In [107]:
with h5py.File(base+'/snapshot_214.100.hdf5', 'r') as f:
    print(f.keys())
    print(f['Header'].attrs.keys())
    npart_total = f['Header'].attrs['NumPart_Total']
    npart = f['Header'].attrs['NumPart_ThisFile']

    ids = f['PartType1']['ParticleIDs'].astype('uint64')[:npart[1]]
    sel = ids % 8 == 0

    with h5py.File(base+'/red_snapshot_214.100.hdf5', 'w') as g:
        g.create_dataset('Config', shape=(0,))
        for key, value in f['Config'].attrs.items():
            g['Config'].attrs[key] = value

        g.create_dataset('Parameters', shape=(0,))
        for key, value in f['Parameters'].attrs.items():
            g['Parameters'].attrs[key] = value

        # PartType0
        ind_0 = np.random.randint(0, npart[0], int(npart[0]/8))
        g.create_dataset('PartType0/Coordinates', data=f['PartType0']['Coordinates'][()][ind_0], dtype=np.float32)
        g.create_dataset('PartType0/Velocities', data=f['PartType0']['Velocities'][()][ind_0], dtype=np.float32)
        g.create_dataset('PartType0/Masses', data=f['PartType0']['Masses'][()][ind_0], dtype=np.float32)

        # PartType1
        g.create_dataset('PartType1/Coordinates', data=f['PartType1']['Coordinates'][()][sel], dtype=np.float32)
        g.create_dataset('PartType1/Velocities', data=f['PartType1']['Velocities'][()][sel], dtype=np.float32)

        # PartType4
        ind_4 = np.random.randint(0, npart[4], int(npart[4]/8))
        g.create_dataset('PartType4/Coordinates', data=f['PartType4']['Coordinates'][()][ind_4], dtype=np.float32)
        g.create_dataset('PartType4/Velocities', data=f['PartType4']['Velocities'][()][ind_4], dtype=np.float32)
        g.create_dataset('PartType4/Masses', data=f['PartType4']['Masses'][()][ind_4], dtype=np.float32)

        # PartType5
        ind_5 = np.random.randint(0, npart[5], int(npart[5]/8))
        g.create_dataset('PartType5/Coordinates', data=f['PartType5']['Coordinates'][()][ind_5], dtype=np.float32)
        g.create_dataset('PartType5/Velocities', data=f['PartType5']['Velocities'][()][ind_5], dtype=np.float32)
        g.create_dataset('PartType5/Masses', data=f['PartType5']['Masses'][()][ind_5], dtype=np.float32)

        g.create_dataset('Header', shape=(0,))
        for key, value in f['Header'].attrs.items():
            if key == 'NumPart_ThisFile':
                g['Header'].attrs[key] = [len(sel), ind_0.shape[0], ind_4.shape[0], ind_5.shape[0]]
            elif key == 'NumPart_Total':
                g['Header'].attrs[key] = np.array( f['Header'].attrs['NumPart_Total'] / 8, dtype=np.uint64)
            else:
                g['Header'].attrs[key] = value


<KeysViewHDF5 ['Config', 'Header', 'Parameters', 'PartType0', 'PartType1', 'PartType4', 'PartType5']>
<KeysViewHDF5 ['BoxSize', 'MassTable', 'NumFilesPerSnapshot', 'NumPart_ThisFile', 'NumPart_Total', 'Redshift', 'Time']>


In [117]:
with h5py.File(base+'/red_snapshot_214.100.hdf5', 'r') as f:
    print(f.keys())
    print(f['Header'].attrs['NumPart_ThisFile'])
    print(f['Header'].attrs['NumPart_Total'])

    print(f['PartType1']['Coordinates'][1])

<KeysViewHDF5 ['Config', 'Header', 'Parameters', 'PartType0', 'PartType1', 'PartType4', 'PartType5']>
[127266562  15224786    551273      1934]
[ 9641742647 10077696000           0           0   353724494     1236689]
[ 11.077132 117.05058  417.1503  ]


In [119]:
with h5py.File(base+'/snapshot_214.100.hdf5', 'r') as f:
    print(f.keys())
    print(f['Header'].attrs['NumPart_ThisFile'])
    print(f['Header'].attrs['NumPart_Total'])

    print(f['PartType1']['Coordinates'][np.where(sel)[0][1]])

<KeysViewHDF5 ['Config', 'Header', 'Parameters', 'PartType0', 'PartType1', 'PartType4', 'PartType5']>
[121798289 127266562         0         0   4410188     15477]
[77133941179 80621568000           0           0  2829795953     9893517]
[ 11.077132 117.05058  417.1503  ]
